### ISSUE TITLE
Parsing failed

### ISSUE THREAD

**Issue by Luthaf** [hansec/fortran-language-server#10]
I just tried this package, and I got a parser error on https://github.com/chemfiles/chemfiles.f03/blob/29ecc3f0830c82172ab27bb9b7ae94a5b5eb1083/src/generated/cenums.f90.

Here is the debug output of the parser:

```
$ fortls --debug_parser --debug_filepath src/generated/cenums.f90

Testing parser
  File = "src/generated/cenums.f90"
  Detected format: free

=========
Parser Output
=========

Traceback (most recent call last):
  File "/home/guillaume/.local/bin/fortls", line 11, in <module>
    sys.exit(main())
  File "/home/guillaume/.local/lib/python2.7/site-packages/fortls/__init__.py", line 77, in main
    ast_new = process_file(contents_split, True, fixed_flag, True)
  File "/home/guillaume/.local/lib/python2.7/site-packages/fortls/parse_fortran.py", line 456, in process_file
    file_obj.add_variable(new_var)
  File "/home/guillaume/.local/lib/python2.7/site-packages/fortls/objects.py", line 592, in add_variable
    self.current_scope.add_child(new_var)
AttributeError: 'NoneType' object has no attribute 'add_child'
```

The file is not compilable on it's own, but must be included in another file, so that might be the origin of the issue.

**Comment by hansec** [comment]
Thanks for the report. Yes, the issue is that this file is not a valid Fortran file on its own. I will look into how to best handle `include` statements like those in the parent file.

**Comment by hansec** [comment]
I just released an update (0.3.5) that should fix the parsing errors you encountered. I am still working to handle include statements, but in the meantime this should improve things. Let me know if you run into continuing parsing issues after updating `fortls` to version 0.3.5.

**Comment by Luthaf** [comment]
This seems to be working, thanks!

**Comment by hansec** [comment]
Thanks for the report. The failure you are observing should have been fixed in version `0.3.5`. Can you make sure you are using the newest version `0.3.7`? There is still a bug in the most recent version related to visibility statements in `#include`d files, but I have a fix for it (see issue #16). But, this failure occurs [in get_object](https://github.com/hansec/fortran-language-server/blob/d88d569f36faae57a619316fdb820745b682efb0/fortls/objects.py#L769) not where you observed the error.

If you still see the error above, in `add_private`, with version `0.3.7` can you create a minimal test file produces the error? If the code is publicly available you can just send me a link too. I was unable to reproduce the error using version `0.3.7`, at least with my guess example in issue #16.

**Comment by unpairedbracket** [comment]
The code isn't public unfortunately, but this is the simplest test case that seems to break the parser as I observed:
```fortran
type t_test
  integer i
end type t_test

public :: t_test
```
The issue does not appear when the variable whose visibility is modified is an `integer`, so it seems to be an issue only in setting visibility of a declared `type`. Here is the parser debug output in case it proves helpful:
```
> fortls --version
0.3.7

> fortls --debug_parser --debug_filepath example2.f03

Testing parser
  File = "example2.f03"
  Detected format: free

=========
Parser Output
=========

type t_test !!! TYPE statement(3)
integer i !!! VARIABLE statement(4)
end type t_test !!! END scope(5)
Traceback (most recent call last):
  File "C:\Python27\Scripts\fortls-script.py", line 11, in <module>
    load_entry_point('fortran-language-server==0.3.7', 'console_scripts', 'fortls')()
  File "c:\python27\lib\site-packages\fortls\__init__.py", line 78, in main
    ast_new = process_file(contents_split, True, fixed_format=fixed_flag, debug=True)
  File "c:\python27\lib\site-packages\fortls\parse_fortran.py", line 582, in process_file
    file_obj.add_public(word)
  File "c:\python27\lib\site-packages\fortls\objects.py", line 722, in add_public
    self.public_list.append(self.enc_scope_name+'::'+name)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by hansec** [comment]
Great, thanks! I think I have tracked down this bug as well (issue #17). I will include the fix in the next release. If you run into more issues can you make a new issue or add to the update issue for this bug (#17)?

**Comment by unpairedbracket** [comment]
Sure, thanks! There are some other (less important) corner cases I think I might have found where the server flags things that will compile as errors, but I'll need to do a bit of investigating to figure out whether it's a language server bug or just bad Fortran. I'll open a new issue if it's the former.
