### ISSUE TITLE
Procedure argument completion

### ISSUE THREAD

**Issue by mcocdawc** [hansec/fortran-language-server#112]
I am using:
Neovim: 0.3.5
fortls: 1.8.2

and have a similar issue like [here](https://github.com/autozimu/LanguageClient-neovim/issues/737)

Simply, when I complete a function which has arguments I get explicit placeholders and I couldn't find a way to rewind through them e.g.:

```fortran
subroutine incr(a)                                                              
    integer, intent(inout) :: a(:)
    a = a + 1                                                                     
end subroutine

call incr(${1:a})
```
I would expect either no placeholders like in vanilla deoplete or some way to jump through various arguments until all placeholders are gone without leaving Insert mode.

**Comment by mcocdawc** [comment]
Thank you for the fast work on it! (And for this great program in general. ;-) )


I think it makes more sense if the snippet is:
```python
                  if self.autocomplete_no_snippets:                                    
                      snippet = ''  
```
instead of `snippet = call_sig`.
At the moment It completes the whole signature which requires usually to delete it.
and this is not what I expect from an option  ` --autocomplete_no_snippets`.

If one does this change, then 
```vim
  call plug#begin('~/.local/share/nvim/plugged')
  
  Plug 'autozimu/LanguageClient-neovim', {
                  \ 'branch': 'next',
                  \ 'do': 'bash install.sh',
                  \ }
          let g:LanguageClient_autoStart = 1
          let g:LanguageClient_autoStop = 0
          let g:LanguageClient_hasSnippetSupport = 0
          let g:LanguageClient_serverCommands = {
                          \ 'python': ['pyls'],
                          \ 'fortran': ['fortls', '--symbol_skip_mem', '--incremental_sync',
                          \             '--lowercase_intrinsics', '--autocomplete_no_snippets']
                          \ }
  
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
    let g:deoplete#enable_at_startup = 1
  Plug 'Shougo/neosnippet.vim'
    " Plugin key-mappings.
    " Note: It must be "imap" and "smap".  It uses <Plug> mappings.
    imap <C-k>     <Plug>(neosnippet_expand_or_jump)
    smap <C-k>     <Plug>(neosnippet_expand_or_jump)
    xmap <C-k>     <Plug>(neosnippet_expand_target)
  
    " SuperTab like snippets behavior.
    " Note: It must be "imap" and "smap".  It uses <Plug> mappings.
    imap <expr><TAB>
     \ pumvisible() ? "\<C-n>" :
     \ neosnippet#expandable_or_jumpable() ?
     \    "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
    smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
    \ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
  
    " For conceal markers.
    if has('conceal')
      set conceallevel=2 concealcursor=niv
    endif
  Plug 'Shougo/neosnippet-snippets'
  Plug 'Shougo/echodoc.vim'
          set cmdheight=2
          let g:echodoc#enable_at_startup = 1
          let g:echodoc#type = 'signature'
          set signcolumn=yes
  call plug#end()

```
leads to a nice behaviour for Fortran subroutines. (And only for them)
The call signature does not interrupt your typing flow, but is displayed at the bottom of the screen.
(Of course it would be even nicer to <TAB> through the parameters in insert mode, but from my limited understanding this requires some changes in neovim + language_client.)


While using these settings I found a bug (I can open a new Issue for this):
The display of the call signature is available **only for subroutines** not for functions. I don't know if
```fortran
subroutine incr(arg)                                                              
    integer, intent(inout) :: arg(:)
    arg = arg + 1                                                                     
end subroutine

integer function test_function(x)
    integer, intent(in) :: x
    f = 2 * x
end function

! Correctly displays the signature at the bottom of the screen.
call incr(
! Does not display the signature.
f(
```

**Comment by hansec** [comment]
I think people like getting the call signature in the autocomplete, however it is obviously a subjective thing. On most platforms, when `signatureHelp` is supported, only the name is completed and the signature is provided as a separate pop-up (as you mentioned). However, it looks like the NeoVim client doesn't support `signatureHelp` at this time. I could add an additional option to autocomplete only the subroutine/function name, which I believe will give you the desired behavior.

As for the `echodoc` behavior, I don't _think_ this is an issue with the language server. It is hard to tell completely but I think `echodoc` must be using some other mechanism to extract signatures, since it doesn't appear to interact with the language server client at all. However, I am not super familiar with Vim plugins and I didn't dig too deep so I certainly could be wrong. Even if it does though, I am pretty sure this would be an issue with how `echodoc` handles things since `signatureHelp`, autocomplete, etc. work as expected for both functions/subroutines.

**Comment by mcocdawc** [comment]
> I could add an additional option to autocomplete only the subroutine/function name, which I believe will give you the desired behavior.

That would be great. Thank you! Of course it is a subjective thing, but I am pretty sure, that I am not the only one who would like to use your tool in that way. (And actually I could solve it for myself in my local `fortls`.)

> since signatureHelp, autocomplete, etc. work as expected for both functions/subroutines.

Did they work for you from inside neovim or another editor?

**Comment by mcocdawc** [comment]
Apparently the echodoc documentation says:
```
  g:echodoc#type                          g:echodoc#type                              
                  The documentation display type.                                     
                  "echo": It uses the command line :echo.                             
                  "signature": It uses gonvim signature feature.                      
                  https://github.com/dzhou121/gonvim                              
                  "virtual": It uses neovim virtual text feature.                 
                  nvim_buf_set_virtual_text()                                     
                                                                                  
                  Default: "echo"    
```
So it seems to act independent of the language server client.

**Comment by Shougo** [comment]
`g:echodoc#type` is for only display type.

**Comment by mcocdawc** [comment]
The issue with echodoc is solved. I made the mistake of testing one character function names. This works with echodoc.
```fortran
integer function double(x)
    integer, intent(in) :: x
    double = 2 * x
end function
```

So a `-autocomplete_name_only` option is the only missing piece now. 
I make a PullRequest in the same way as your `-autocomplete_no_snippets` commit.
