### ISSUE TITLE
Help me install and configure it in vim

### ISSUE THREAD

**Issue by rudrab** [hansec/fortran-language-server#114]
Hi,
I am trying to install and configure it to be able to use it in my vim.
https://paste.fedoraproject.org/paste/cnFlSBgBMJDOhVp1UnVLQA is my complete `vimrc`

I have also followed https://github.com/hansec/fortran-language-server/wiki/Using-forts-with-vim

But still, I am not getting any autocompletion.

Any help, please?

**Comment by MagB93** [comment]
Hi,

what I could tell just from your ```.vimrc``` is that you are missing the install commands necessary 
for it to work. Have you followed the steps at [LanguageClient-neovim/Install.md](https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md)

Best regards

Magnus

**Comment by rudrab** [comment]
MagB93:
Thanks for your reply. I have moved from vundle to vim-plug only  to get lsp support, 
My forls is running perfectly, and the corresponding vimrc is:
```
Plug 'autozimu/LanguageClient-neovim', {
      \ 'branch': 'next',
      \ 'do': 'bash install.sh',
      \ }
```
and:
```
set hidden

let g:LanguageClient_serverCommands = {
    \ 'rust': ['~/.cargo/bin/rustup', 'run', 'stable', 'rls'],
    \ 'javascript': ['/usr/local/bin/javascript-typescript-stdio'],
    \ 'javascript.jsx': ['tcp://127.0.0.1:2089'],
    \ 'python': ['/usr/local/bin/pyls'],
    \ 'ruby': ['~/.rbenv/shims/solargraph', 'stdio'],
    \ 'fortran': ['fortls', '--symbol_skip_mem', '--incrmental_sync', '--autocomplete_no_prefix'],
    \ }
```

**Comment by rudrab** [comment]
MagB93:
A detailed bug report is created at https://github.com/autozimu/LanguageClient-neovim/issues/832
Can you kindly have a look?

**Comment by hansec** [comment]
Unfortunately, I am not too familiar with Vim plugins. I only really use Vim in remote environments with not bells and whistles set up.

@MagB93 Is there somewhere the Fortran setup for Vim is documented (other than the out of date on this project's wiki)? If not, maybe I should update the current wiki setup for Vim. Contributions and suggestions from users are always welcome to keep those items up to date.

**Comment by MagB93** [comment]
@rudrab Maybe there is an issue regarding the algorithm for 
finding the root directory. For example [ccls](https://github.com/MaskRay/ccls/wiki/LanguageClient-neovim) has some additional settings inside a ```$HOME/.config/nvim/settings.json``` file.
I will have a more detailed look tomorrow. 

Speaking of that @hansec I still have to update the wiki for emacs. Sorry for the delay.

**Comment by MagB93** [comment]
@rudrab So how it you solve it?

**Comment by rudrab** [comment]
@MagB93 : I am using the vimrc given in #123 . But, as said, its bit slow to start. Once started, its fine.
