### ISSUE TITLE
Incorrect symbol kind of module functions

### ISSUE THREAD

**Issue by letmaik** [hansec/fortran-language-server#117]
The server returns "method" as symbol kind for functions in a module. The correct symbol kind should be "function" here as "method" is reserved for usage in classes. In the context of Fortran, "method" should only be used for type-bound procedures (see bottom of http://fortranwiki.org/fortran/show/Object-oriented+programming).

**Comment by hansec** [comment]
It should return "method" for subroutines and "function" for functions. I did this to distinguish subroutines and functions, but in hindsight I think you are right and everything should be marked as "function" unless it is in a defined-type.
