### ISSUE TITLE
Handling of multi-line comment description

### ISSUE THREAD

**Issue by AndreHorst** [hansec/fortran-language-server#118]
When having a multi-line description of an object (variable, function, etc.):
![fls_1](https://user-images.githubusercontent.com/25814609/59915539-252a4380-941d-11e9-9465-907a639b153c.png)

the tooltip when hovering the variable it only showing the comment lines below the declaration. Is that a feature or a bug?
![fls_2](https://user-images.githubusercontent.com/25814609/59915600-4b4fe380-941d-11e9-9ab2-c63e24535d6c.png)

**Comment by hansec** [comment]
That is definitely a bug. Thanks for the report!

**Comment by AndreHorst** [comment]
Ok thanks! 
Still, can you confirm it's a bug in the language server? I'm using vscode with the Fortran Intellisense extension, so the bug might be even there. I didn't think of that while writing this issue here.

Keep up the greet work!

**Comment by hansec** [comment]
Yeah, it was an issue with the language server. It should now be fixed (see commit above) in the next release branch `v1.10`. Thanks for the report!

**Comment by AndreHorst** [comment]
Thanks! Great job!
