### ISSUE TITLE
Rename Symbol is inconsistent

### ISSUE THREAD

**Issue by AndreHorst** [hansec/fortran-language-server#124]
Hello!
I just tried "Rename Symbol" to change a variable name across the project. 

**(Just to clarify, this is essentially a refactoring process, correct?)**

Anyway, sometimes it renames the symbol, but sometimes not and then not even in the same file. Unfortunately, I could not find a pattern so far, sorry.

**Steps:**
Pressing F2 (or right-click "Rename Symbol") in order to rename
**MAIN_PLUGIN_ROOT_FOLDER** to **test_MAIN_PLUGIN_ROOT_FOLDER**

![fortls_issue_1](https://user-images.githubusercontent.com/25814609/60723250-6fd6b000-9f33-11e9-946a-0e152bbcbaf5.png)

The variable which I selected gets renamed accordingly:
![fortls_issue_2](https://user-images.githubusercontent.com/25814609/60723491-099e5d00-9f34-11e9-9e34-c04b70f12cc8.png)

However, further down the same source file, it sometimes apply the change, and sometimes not:
![fortls_issue_3](https://user-images.githubusercontent.com/25814609/60723529-25a1fe80-9f34-11e9-9c86-6da7db1f6d56.png)

Am I doing something wrong or is this a bug?

Hope to hear from you soon!

**Comment by hansec** [comment]
Thanks for the report! I suspect this is a bug, likely due to the fairly complicated nature of that source line. Can you add a couple of source code examples here (not screenshots) where this does not work?

**Comment by AndreHorst** [comment]
Alright, I narrowed it down! And it's weird ;-) 

Apparently, renaming the symbol does not work of the following two conditions apply:
1. You use it in a write statement, **combined with other strings**
2. a **single preceding** string contains a single quotation mark **'**

Example:

Originial State, **prior** to "rename symbol":
```fortran
   character(len=255) :: ORIGINAL_NAME

    ! << "rename-symbol" works
    ORIGINAL_NAME = "Testing"

    ! << "rename-symbol" works
    write(*,*) ORIGINAL_NAME 
    
    ! << "rename-symbol" works
    write(*,'(A)') "This is a test with NO quotation mark in this string:  ",trim(adjustl(ORIGINAL_NAME)) 

    ! << "rename-symbol" does not work
    write(*,'(A)') "This is also a test, but with a quotation mark BEFORE the variable call: ' ", trim(adjustl(ORIGINAL_NAME)) 

    ! << "rename-symbol" works
    write(*,'(A)') "This is also a test, but with a quotation mark BEFORE the variable call: ' ","a second quotation mark: ' ", trim(adjustl(ORIGINAL_NAME)) 

     ! << "rename-symbol" works
    write(*,'(A)') trim(adjustl(ORIGINAL_NAME)), "This is also a test, but with a quotation mark ' after the variable call"
```

Changed State, **after** using "rename symbol":
```fortran
  character(len=255) :: RENAMED_VARIABLE_NAME 

    ! << "rename-symbol" works
    RENAMED_VARIABLE_NAME  = "Testing"

    ! << "rename-symbol" works
    write(*,*) RENAMED_VARIABLE_NAME  
    
    ! << "rename-symbol" works
    write(*,'(A)') "This is a test with NO quotation mark in this string:  ",trim(adjustl(RENAMED_VARIABLE_NAME )) 

    ! << "rename-symbol" does not work
    write(*,'(A)') "This is also a test, but with a quotation mark BEFORE the variable call: ' ", trim(adjustl(ORIGINAL_NAME)) 

    ! << "rename-symbol" works
    write(*,'(A)') "This is also a test, but with a quotation mark BEFORE the variable call: ' ","a second quotation mark: ' ", trim(adjustl(RENAMED_VARIABLE_NAME )) 

     ! << "rename-symbol" works
    write(*,'(A)') trim(adjustl(RENAMED_VARIABLE_NAME )), "This is also a test, but with a quotation mark ' after the variable call"
```

I hope you can work with that? If not, please let me know how I can help!

**Comment by AndreHorst** [comment]
Another example:

Originial State, **prior** to "rename symbol":
```fortran
    character(len=255) :: ORIGINAL_NAME

    call do_someting("test ' ",0,file_id,cbuf,ORIGINAL_NAME)
    call do_someting("test ' ' ",0,file_id,cbuf,ORIGINAL_NAME)
    call do_someting("test",0,file_id,cbuf,ORIGINAL_NAME," ' ")
```

Changed State, **after** using "rename symbol":
```fortran
    character(len=255) :: RENAMED_VARIABLE_NAME 

    call do_someting("test ' ",0,file_id,cbuf,ORIGINAL_NAME)
    call do_someting("test ' ' ",0,file_id,cbuf,RENAMED_VARIABLE_NAME )
    call do_someting("test",0,file_id,cbuf,RENAMED_VARIABLE_NAME ," ' ")
```

**Comment by hansec** [comment]
Thanks for all the great test cases! I will look into it the next time I get a chance.

**Comment by AndreHorst** [comment]
Awesome!
