### ISSUE TITLE
FORTLS not launching

### ISSUE THREAD

**Issue by sebfet** [hansec/fortran-language-server#125]
Hey,
I downloaded the extensions for Visual Studio Code and set the paths to launch fortls on application start.
Now i get the error message: [Error - 2:45:51 PM] Server initialization failed.
  Message: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
  Code: -32603 

I am using Modern Fortran 2.1.1 with FORTRAN IntelliSense 0.6.0. 
What could be the reason and the fix for this issue?

**Comment by hansec** [comment]
This is a file encoding issue. Unfortunately, it is not easy to handle all possible file encodings gracefully. Is the source code where you see the error open source? Also, what version of Python are you using?

**Comment by JayPBe** [comment]
In my very specific case, we have a git repo which is subdivided into a fortran source folder and folders which include documentation, license manager and all kinds of other stuff.
Initially I got the exact same error when I chose my working folder in VSC to be the top folder of our repo, which included all the above mentioned stuff. Something within the non-source-code folders must've messed up the language server.
In case you have a similar structure, I'd suggest you try to load only the folder with source code into VSC.

**Comment by sebfet** [comment]
The fix described by JayPBe helped in my case as well. So setting the Workspace for just the subfolder containing the source code worked but consequently I am missing out on some source files related to the project but not the main code. Currently using python 2.7.5, I have no idea why though.

**Comment by hansec** [comment]
Hmmmm, actually this should be caught for just the file where the encoding error occurred. It shouldn't prevent initialization of the whole workspace. Can you try doing a [debug initialization](https://github.com/hansec/fortran-language-server/wiki/Debugging-server-initialization-errors) with the same root directory where you see the error? This should give you a more complete stack trace to show where exactly the error is occurring. Thanks!

**Comment by Qicang** [comment]
The code on line 140 and 141 in objects.py
   `                         if new_rename is not None: 
                            use_dict[use_stmnt.mod_name].rename_map = new_rename`
produce the can't set attribute error

**Comment by hansec** [comment]
@Qicang That bug should now be fixed in the most recent patch (v1.10.2). If you continue to see this or other errors please open a new issue. Thanks for the report!

**Comment by vdikan** [comment]
@hansec Thank you, I'm glad to report that v1.10.2 solved this issue for me!
(emacs + lsp-mode + fortls with python3)
