### ISSUE TITLE
Semicolon not recognized in if-clause

### ISSUE THREAD

**Issue by AlKa93** [hansec/fortran-language-server#127]
The first program is interpreted correctly - no errors.

    program test1
    integer ::  a
    a=0; a=1;
    end program test1
The second one says "unexpected end of scope" at the endif. 

    program test2
    integer ::  a
    logical ::  l
    if(l) then; a=0
    elseif(.not.l) then; a=1
    endif
    end program test2
So formatting if-clauses with semicolons confuses fortls and makes reference links useless. This is very annoying.

**Comment by hansec** [comment]
Thanks for the report. This should now be fixed in master and will be included in the next patch. Let me know if you continue to see this or any other issues.

**Comment by AndreHorst** [comment]
THANKS! Found that one too, but the semicolon was in a #include statement, so I thought it had something to do with the preprocessor thing. 

![includes](https://user-images.githubusercontent.com/25814609/61117978-1113b800-a498-11e9-863b-cb706016f5bf.png)
Looking forward to the patch!
