### ISSUE TITLE
Old style character array declaration with star not recognized

### ISSUE THREAD

**Issue by letmaik** [hansec/fortran-language-server#134]
Example from some old code:
```fortran
CHARACTER, INTENT(IN)    :: S*(*)
```
And the error is:
> Variable "S*" with INTENT keyword not found in argument list

This may be related to #130 but it looks like a separate issue.

**Comment by chyiever** [comment]
so, do you get a good solution about this problem now? I faced this bug too.

**Comment by gnikit** [comment]
I believe it has been fixed. Could you mention your `fortls` version, any user settings and also post a minimal working example?
