### ISSUE TITLE
Preprocessor define replaces parts of token

### ISSUE THREAD

**Issue by manie204** [hansec/fortran-language-server#141]
The parser for preprocessor defines (specified in .fortls) wrongly replaces parts of single tokens. Here is what I mean by that. Given the source file
```Fortran
#define FOO replaced_1
#define BAR replaced_2
FOO
FOO_abc
FOO_BAR
```
Intellisense lists the following symbols:
```Fortran
replaced_1
replaced_1_abc
replaced_1_replaced_2
```
However, it should be:
```Fortran
replaced_1
FOO_abc
FOO_BAR
```

**Comment by hansec** [comment]
Thanks for the report! This should now be fixed in master and will be included in the next patch.
