### ISSUE TITLE
Hover information without Syntax Highlighting

### ISSUE THREAD

**Issue by AndreHorst** [hansec/fortran-language-server#160]
It is not a critical issue, however this worked before! The hover-information is not showing syntax highlighting for the variable type:

![grafik](https://user-images.githubusercontent.com/25814609/78638464-9e136280-78ac-11ea-9cbd-c56fba8252c2.png)

![grafik](https://user-images.githubusercontent.com/25814609/78638682-f9ddeb80-78ac-11ea-8bba-d167b04a7f77.png)

**Comment by hansec** [comment]
Thanks for the report. Are you using VSCode? If so, this was actually a bug with the extension for that editor, see [#21](https://github.com/hansec/vscode-fortran-ls/issues/21).

**Comment by AndreHorst** [comment]
Yes, I am using VSCode! OK thanks, I should have checked the other issues first. Can be closed then and I am waiting for the next patch :-)

**Comment by AndreHorst** [comment]
All good! Thanks!
