### ISSUE TITLE
semicolon and syntax-highlightning in if-else

### ISSUE THREAD

**Issue by AlKa93** [hansec/fortran-language-server#161]
There seems to be a highlightning issue with the semi-colon notation. Both lines are valid fortran.

![screenshot](https://user-images.githubusercontent.com/31747915/78680851-4dbbf500-78ec-11ea-8a90-f42bbb3675e9.png)

**Comment by hansec** [comment]
Hi @AlKa93, the language server does not provide syntax highlighting. You should report this bug to the "base" Fortran language package for your editor. For example, [Modern Fortran](https://marketplace.visualstudio.com/items?itemName=krvajalm.linter-gfortran) or [fortran](https://marketplace.visualstudio.com/items?itemName=Gimly81.fortran) for VSCode.
