### ISSUE TITLE
Fortls shows no matching begining

### ISSUE THREAD

**Issue by Jim-215-Fisher** [hansec/fortran-language-server#172]
In submodule, 'end module procedure' clause shows no matched beginning. In fact, 'end module procedure' matched 'submodule'  clause instead of  'module procedure' clause

**Comment by hansec** [comment]
Thanks for the report and sorry for the delay. This certainly sounds like a bug, but I am not exactly sure what you are describing. Can you provide a short code snippet that demonstrates this problem? Thanks!

**Comment by Jim-215-Fisher** [comment]
`submodule(T1) T2
contains
module procedure test
...
end module procedure test
end submodule T2`
 In this snippet, 'end module procedure test' is not matched with 'module procedure test' but 'submodule(T1) T2' in Fortls.

**Comment by hansec** [comment]
Great, thanks for the snippet. I am now able to reproduce this and will hopefully have a fix shortly.
