### ISSUE TITLE
Handling of generic procedure interfaces

### ISSUE THREAD

**Issue by unpairedbracket** [hansec/fortran-language-server#18]
When declaring a generic procedure interface, the generic interface having the same name as one of the contained procedures can trigger a `Variable declared twice in scope` error from `fortls`. I thought this may just be incorrect fortran (it definitely seems bad and confusing) but `gfortran -c test.f03` compiles without errors and doesn't complain even with `-Wall` specified (`crayftn` also has no issues), so I think it must be acceptable. Not a massive issue as it doesn't cause parsing to fail, but detecting this specific case and demoting to a warning might be useful for agreement with the compiler.

```fortran
module m_test

interface test_proc
    module procedure test_proc
end interface test_proc

contains

subroutine test_proc( )
end subroutine test_proc

end module m_test
```

**Comment by hansec** [comment]
Thanks for the report. This is a really strange case, since the interface definition is entirely superfluous. I will look in to preventing the error diagnostic when this is encountered occur though.

**Comment by PaulXiCao** [comment]
I came along the same error and found some more info.

The interface name can even be different and the error message will still be thrown but only if one uses ``procedure test_proc`` instead of ``module procedure test_proc``.

In short: This will throw an error
```fortran
module m_test

interface operator(==)
  procedure test_proc
end interface operator(==)

contains

subroutine test_proc( )
end subroutine test_proc

end module m_test
```
whereas this runs smoothly
```fortran
module m_test

interface operator(==)
  module procedure test_proc
end interface operator(==)

contains

subroutine test_proc( )
end subroutine test_proc

end module m_test
```
