### ISSUE TITLE
Non standard variable types e.g. PETSc not recognised as variables

### ISSUE THREAD

**Issue by gnikit** [hansec/fortran-language-server#185]
Hi

I have noticed that when a variable type, like Mat or PC from PETSc is used as an input argument to a subroutine or a function or even a local variable, the language server fails to recognise it all together as a variable

```fortran
module multigrid

  use petsc

  implicit none
  subroutine DestroyMultigrid(prec)
    PC, intent(inout):: prec
  
    PetscErrorCode ierr
    PCType pctype
    PC subprec
    
    call PCGetType(prec, pctype, ierr)
    if (pctype==PCCOMPOSITE) then
      ! destroy the real mg
      call PCCompositeGetPC(prec, 0, subprec, ierr)
      ! destroy the internal mg
      call PCCompositeGetPC(prec, 1, subprec, ierr)
      call DestroyInternalSmoother()
    end if
    
  end subroutine DestroyMultigrid

end module multigrid
```

**Comment by gbogopolsky** [comment]
Hello, 

I had the same question and I managed to find more info about this in another issue, with a functional workaround: https://github.com/hansec/fortran-language-server/issues/115#issuecomment-506767486

I simply added the PETSc types that I needed. They are now recognized as variables of PETSCINT type for example.  
Just a caveat, the syntax coloration of the `::` is not done for those cas, but it is good enough for my use.

Parsing the header files for type definition would be a better solution, but I don't know where the work on this feature is.

**Comment by gnikit** [comment]
Hi @gbogopolsky,

Thank you for the suggestion and the issue link, it is a substantial improvement from before. However, I cannot help but wonder if we could automate the parsing of the preprocessor directives by just including the Fortran header files holding these definitions. I might have a play with that idea in the near future and report any meaningful progress. 

Until then, I am closing this issue. Thanks again.
