### ISSUE TITLE
Parser problem after / in FORMAT statement

### ISSUE THREAD

**Issue by gedrite** [hansec/fortran-language-server#19]
I do not have a detailed understanding of FORMAT statements, but I have noticed that the / in the Format statement below affects syntax coloring in both Atom and VSCode, so I assume it might be a problem with fortran-language-server. 

WRITE (out,1031) IMEGA,FFX,BREMS,(DX0(I),I=1,N1)
1031       FORMAT (1X,I4,' FFX,BREMS,DX0:',6(2X,1PE15.8),       &
:,100(/,54X,4(2X,1PE15.8)))                                                               ! problem is / in this line

After the /, which is used to mark eor to start a new line of output, all of the fortran keywords like CALL, WRITE, SUBROUTINE, etc are colored incorrectly. This is in both VSCode and Atom.

Sorry, I am brand new to Atom and don't have the fls debugger output to send along with this report; I hope the above is enough to track down the problem.

**Comment by hansec** [comment]
Thanks for the report, however syntax highlighting is handled by different packages. The syntax highlighting components are provided by the Atom package ["language-fortran"](https://atom.io/packages/language-fortran) and Visual Studio Code package ["fortran"](https://marketplace.visualstudio.com/items?itemName=Gimly81.fortran) respectively. You should file a bug report with those packages to address this issue.
