### ISSUE TITLE
Specifing different object directory other than the source directory for the object file and .mod file

### ISSUE THREAD

**Issue by Koushikphy** [hansec/fortran-language-server#193]
I'm using fortran-language-server with vscode. It creates `.mod` files in the sources directory for each modules. Usually, when building with makefile I create a different `obj` directory where I put all the `.mod` and `.o` files. can this be done with the `fortls` so that the main sources directory stays clean?

**Comment by gnikit** [comment]
Hi there, so `fortls` does not provide linting in VSCode, that is the job of the underlying Fortran extension, see extension requirements.
If you are using [Modern Fortran](https://github.com/krvajal/vscode-fortran-support) you can do what mentioned in this issue https://github.com/krvajal/vscode-fortran-support/issues/175

**Comment by Koushikphy** [comment]
ok. thanks,
