### ISSUE TITLE
Highlight symbols when hover?

### ISSUE THREAD

**Issue by nujabse** [hansec/fortran-language-server#197]
Fortran-language-server seems not to hightlight symbols when hovering, can this be implemented?

**Comment by gnikit** [comment]
Hi, from what I understand you want something like this right?
![Screenshot from 2021-04-17 09-11-09](https://user-images.githubusercontent.com/16143716/115106561-747c2500-9f5d-11eb-9c8a-56a51e2ffcc5.png)

I would suspect that might be beyond the control of `fortls` and that it varies between code editors and themes. For example in VSCode (and I think Atom but don't quote me on that) that is the default behaviour.

NOTE: Disregard previous answer, I thought this was posted in the VSCode extension repo.

**Comment by nujabse** [comment]
Thanks for the help. I have tested that highlighting symbols works fine on VSCode, but on Emacs with lsp-mode, it does not work. Maybe there is something that I need to further configure. Thanks!

**Comment by gnikit** [comment]
> Thanks for the help. I have tested that highlighting symbols works fine on VSCode, but on Emacs with lsp-mode, it does not work. Maybe there is something that I need to further configure. Thanks!

I updated my answer, sorry I thought this was posted on the VSCode repo :disappointed_relieved:
