### ISSUE TITLE
False positive: Object not found in scope in case of "USE, NON_INTRINSIC"

### ISSUE THREAD

**Issue by zaikunzhang** [hansec/fortran-language-server#206]
First of all, thank you for this great work!

With `fortls 1.12.0`, I get a false positive about "Object not found in scope". Here is a minimal working example. 

```
!  testls.f90
module kind_mod
implicit none
private
public :: DP
integer, parameter :: DP = kind(0.0D0)
end module kind_mod

program testls
use, non_intrinsic :: kind_mod, only : DP
! If the last line is changed to `use kind_mod, only : DP`, then there is no problem.
implicit none
real(DP) :: x  ! fortls complains that `Object "dp" not found in scope`
x = 0.0_DP
end program testls
```

`fortls` complains that `Object "dp" not found in scope` in the program `testls`. The complaint will disappear if we replace
```
use, non_intrinsic :: kind_mod, only : DP
```
with
```
use kind_mod, only : DP
```

Thank you for your attention.

**Comment by gnikit** [comment]
You are indeed onto something, it would appear that the regex handling `use` statements only contains `INTRINSIC`.
see: https://github.com/hansec/fortran-language-server/blob/e8479e89cf36c7fea5fed94cf5cb2de6c867ff51/fortls/parse_fortran.py#L17
I suspect that this might be a bigger pain than simply doing `INTRINSIC|NON_INTRINSIC` and `read_use_stmt` might need a small edit as well.

**Comment by zaikunzhang** [comment]
> I suspect that this might be a bigger pain than simply doing `INTRINSIC|NON_INTRINSIC` and `read_use_stmt` might need a small edit as well.

Thank you, @gnikit , for the response! 

I edited only `USE_REGEX` as you mentioned, but the problem persists. What edition would be needed for `read_use_stmt`?  Sorry that I do not code Python, so I could not figure it out myself. 

Thanks and regards,
Zaikun

**Comment by gnikit** [comment]
The fix for this should be `(INTRINSIC|NON_INTRINSIC)` that is all. I will be pushing a patch in my [fork](https://github.com/gnikit/fortran-language-server)

**Comment by gnikit** [comment]
@zaikunzhang FYI this has been in [`fortls`](https://pypi.org/project/fortls/) since v1.14.3 (currently fortls is in v2.0.1)

**Comment by zaikunzhang** [comment]
Hello @gnikit ! Thank you very much for fixing this issue! Sorry that I missed your previous comment in December. I will try the new version.
