### ISSUE TITLE
handle utf-8 decoding errors in fortls

### ISSUE THREAD

**Issue by kemlath** [hansec/fortran-language-server#21]
In langserver.py have extended the try catch block in def init_file(file path) to also include the two with statements. This handles utf-8 decoding errors in the PY3K relevant code:

`def init_file(filepath):
    #
    try:
        if PY3K:

            with open(filepath, 'r', encoding="utf-8") as fhandle:
                contents = re.sub(r'\t', r'  ', fhandle.read())
                contents_split = contents.splitlines()

        else:
            with open(filepath, 'r') as fhandle:
                contents = re.sub(r'\t', r'  ', fhandle.read())
                contents_split = contents.splitlines()
    #

        fixed_flag = detect_fixed_format(contents_split)
        ast_new = process_file(contents_split, True, filepath, fixed_flag)
    except:
        return None
    else:
        # Construct new file object and add to workspace
        tmp_obj = {
            "contents": contents_split,
            "ast": ast_new,
            "fixed": fixed_flag
        }
        return tmp_obj`

**Comment by hansec** [comment]
Thanks for the suggestion. I have merged in a commit that catches decoding errors and also reports more information on the type of issue when reading, changing, decoding, or parsing a file fails.
