### ISSUE TITLE
Handle old external definitions properly

### ISSUE THREAD

**Issue by grisuthedragon** [hansec/fortran-language-server#220]
Dealing with very old style fortran codes, I have the following situation:
```fortran 
SUBROUTINE X()
EXTERNAL LSAME                                                                                                                  
LOGICAL LSAME
....
END SUBROUTINE 
```
where the language server claims 
```
Error:Variable "LSAME" declared twice in scope 
```
which is not an error in this case.

**Comment by gnikit** [comment]
Duplicate of #169 
This bug has been fixed in `fortls`(https://github.com/gnikit/fortls), a diverged fork I made from fortran-language-server

**Comment by grisuthedragon** [comment]
Thanks, I switched to your fork,
