### ISSUE TITLE
getting completions from Nek5000 although not installed on my system

### ISSUE THREAD

**Issue by zbinkz** [hansec/fortran-language-server#228]
Hi, I'm running fortls in Kate 20.12.2 on Debian Bullseye kernel 5.10.0-16-amd64, and Plasma 5.20.5. Working on a f90 project and I keep getting completions from Nek5000 code although it is not installed on my system. It's github repo can be found [there.](https://github.com/Nek5000/Nek5000)

I tried grepping for anything Nek related in `/usr/lib/python3/dist-packages/fortls/` but no matches.

Has anyone encountered this? This is my first experience with fortls and I installed it from Debian repos, so it should be on stock settings AFAIK.

**Comment by gnikit** [comment]
Are you using `fortran-language-server` or [`fortls`](https://github.com/gnikit/fortls)

**Comment by zbinkz** [comment]
I'm using `fortran-language-server` and this package is based on `fortls`.

```APT-Sources: http://deb.debian.org/debian bullseye/main amd64 Packages
Description: Fortran Language Server for the Language Server Protocol
 Fortran Language Server (fortls) is an implementation of the Language
 Server Protocol. It can be used with editors that supports the
 protocol (e.g. Emacs with elpa-lsp-mode) to offer support for code
 completion and documentation.```

**Comment by gnikit** [comment]
so if you do `fortls --version` you get `1.12.0`? Basically, this repo has been anandonded and we started a new language server called [`fortls`](https://github.com/gnikit/fortls) (for backwards compatibility with existing tools). 

Anyway, as for the issue at hand, if you want you can swap to `fortls` (`pip install fortls`) and open a discussion on the repo, https://github.com/gnikit/fortls/discussions. There is not much point in trying to debug `fortran-language-server` when we can't patch and update the code.

**Comment by zbinkz** [comment]
Yes, I get version `1.12.0`. I'll swap to pip version and check again.
