### ISSUE TITLE
(Neo)vim configuration

### ISSUE THREAD

**Issue by MagB93** [hansec/fortran-language-server#28]
Hi,

I've been able to get the settings for (Neo)vim for the Fortran Language Server using 
[LanguageClient](https://github.com/autozimu/LanguageClient-neovim)

```
let g:LanguageClient_serverCommands = {
    \   'fortran': ['fortls', '--symbol_skip_mem', '--incrmental_sync', '--autocomplete_no_prefix']
    \ }
```

Is it possible to add them to the Wiki/ Readme? Btw. I think that 'incrmental_sync' should be named 
'incremental_sync' or? Atleast the help/ vscode repository both state that way.

**Comment by hansec** [comment]
Thanks for the contribution! I have added a page to the wiki for using the language server with vim. I also corrected the typo you mentioned. The server will also continue to accept the old spelling.
