### ISSUE TITLE
Save failing when there are spaces in the file path

### ISSUE THREAD

**Issue by SNGoBoom** [hansec/fortran-language-server#29]
![screen shot 2018-07-12 at 18 14 11](https://user-images.githubusercontent.com/41171425/42662566-1755091a-8600-11e8-8679-eba2d5a2fa62.png)

When opening or trying to save a .f95 file with Atom the attached error appears.  Removing all spaces in the file path fixes the error.  Note, saving and loading still work fine, that error just appears.

**Comment by hansec** [comment]
Thanks for the report. I just released an updated version (0.7.1) that should fix this issue. Check it out and let me know if the issue persists.

**Comment by SNGoBoom** [comment]
Ok, I have a question and I don't know if it's a bug or if I am being dumb.  The Diagnostics panel doesn't show any issues even when I intentionally put issues it's supposed to catch into my code.  Am I doing something wrong?  I've attached a screen shot and my code, note that the variable start_time is declared twice.

![screen shot 2018-07-13 at 14 19 02](https://user-images.githubusercontent.com/41171425/42707286-b5621664-86a7-11e8-80e9-2bd164d823bd.png)


MODULE helper

    CONTAINS
        FUNCTION probability_finder(n)
            !   Purpose:
            !       To find the probability of n people in a room having the same birthday

            ! declarations
            REAL :: probabiity_finder
            INTEGER, INTENT(IN) :: n            ! number of people
            INTEGER, DIMENSION(n) :: bdays ! the array of birthdays
            INTEGER :: bday ! one single birthday in the array
            REAL, DIMENSION(n) :: rndm ! birthdays normalized between 0 and 1
            INTEGER, PARAMETER :: nsims = 5000 ! number of simulations to run
            INTEGER :: n_dupe ! number with duplicates
            INTEGER :: i,j        ! loop indices

            ! reset variables
            n_dupe=0

            ! loop over each simulation
            sim_loop: DO i = 1, nsims
                ! generate array of birthdays
                CALL RANDOM_NUMBER(rndm)
                bdays = INT(1 + 364*rndm)

                ! check for duplicates
                dup_loop: DO j = 1, n
                    bday = bdays(j)
                    IF (ANY(bdays(i+1:) == bday)) THEN
                        n_dupe = n_dupe + 1
                        EXIT
                    END IF
                END DO dup_loop
            END DO sim_loop

            probability_finder = (REAL(n_dupe) / REAL(nsims))


        END FUNCTION probability_finder
END MODULE helper

PROGRAM birthday_problem
    USE helper
    IMPLICIT NONE !requires me to declare all variables

	!   Purpose:
	!       To find the probability of n people in a room having the same birthday and do so for many values of n
	!       Source: Exercise 7-28

	!   Variable Declarations
    INTEGER :: start_time   ! execution start time
    INTEGER :: end_time     ! execution end time
    REAL    :: prob         ! probability of two people having the same birthday in a group of n people
    INTEGER :: n            ! number of people
    REAL :: start_time 
    !	start timer
    CALL SYSTEM_CLOCK(start_time)

    DO n = 1,40
        prob = probability_finder(n)
        WRITE (*,100) n, 100*prob
        100 FORMAT ('The chance that two people in a group of ', I3, ' people will have the same birthday is ', F6.2,' percent')
    END DO


	!   Finish up.
    CALL SYSTEM_CLOCK(end_time)
    ! execution time
    end_time = end_time - start_time
    WRITE (*,999) end_time/1000., end_time/60000., end_time/3.6E6
    999 FORMAT (/,'Program complete. Time to execute ', F7.3, 's or ', F7.3, 'min or ', F7.3, 'hrs')
END PROGRAM birthday_problem

**Comment by SNGoBoom** [comment]
You're right.  As soon as I saved the file the diagnostics showed up.  Sorry to waste your time, I'm new to Atom and Fortran and haven't quite figured either one of them out yet :)
