### ISSUE TITLE
initialization of arrays with parameter statement seems to be handled incorrectly

### ISSUE THREAD

**Issue by michaelkonecny** [hansec/fortran-language-server#35]
Hi, 
consider the following example:
```
subroutine example()
    implicit none

    real(8), dimension(6), parameter :: eye3 = [1d0, 0d0, 0d0, 0d0, 1d0, 1d0]
    
end subroutine
```

This yields two warnings saying "Variable 0d0 declared twice in scope".
Oddly enough, there have to be at least three zeros in the array to trigger the warning.
Also, it doesn't get triggered for the ones.

**Comment by hansec** [comment]
Thanks for the report. The issue was that the parser didn't support bracket style array initialization like you were using here. I just released a fix (0.8.2) check it out and let me know if you still see the error.
