### ISSUE TITLE
beginnings of strings shouldn't be considered in commented code

### ISSUE THREAD

**Issue by michaelkonecny** [hansec/fortran-language-server#36]
Consider this:
```
! please don't delete this subroutine
subroutine example()
    implicit none

end subroutine
```

fortls seems to think everything starting from `'t delete` is a string, even though the quote is inside a comment.

**Comment by hansec** [comment]
Thanks for the report. What is the symptom you are seeing? When I include this in a module it seems to work just fine in Atom (shows up in outline, autocomplete, etc.).

**Comment by michaelkonecny** [comment]
This is what I get:
![image](https://user-images.githubusercontent.com/4976024/44950506-78f57d00-ae49-11e8-8943-4009979127c3.png)

It seems to work fine if the comment is inside a subroutine, however.

(BTW, I got the VS2017 extension running, just needs a couple of more tweaks to be publishable.)

**Comment by hansec** [comment]
Syntax highlighting isn't provided by the language server so the display issue must be related to the syntax highlighting definition in your extension or whatever extension is providing syntax highlighting in VS2017. Do you see any issues related to autocomplete or other language server functionality?

**Comment by michaelkonecny** [comment]
Oh I see. I'm sorry, I had realised this before, but forgot about it meanwhile.
It's a bug in the TextMate grammar file I included with my extension.
I will try to get that fixed.
