### ISSUE TITLE
more details in variable_hover

### ISSUE THREAD

**Issue by michaelkonecny** [hansec/fortran-language-server#37]
Just having "go to definition" thanks to fortls is great!

However, if variable_hover was improved, that would be even better!

In this example:
```
subroutine test()
    implicit none    

    real(8), dimension(3, 3) :: A
    real(8), dimension(3, 3) :: B ! this is the matrix i'm going to transpose

    A = transpose(B)

end subroutine
```
when I hover over B, could I get:
- the other keywords in the declaration (here: dimension, but could also be intent, parameter, save, ...)
- the comment on that line

like this:
`real(8), dimension(3, 3) ! this is the matrix i'm going to transpose`?

**Comment by hansec** [comment]
The hover should actually show all the keywords already. However, the dimension keyword was not fully supported for explicit sizing, which was tripping up this particular case. I have a fix for this that I will merge in shortly.

I could also add trailing comments to the variable hover information without too much effort. I will work on that as well.

**Comment by michaelkonecny** [comment]
Terrific.

I have also run into a piece of code that makes VS with my extension crash completely, but I haven't found out whether it's a problem on the server side or Microsoft's Client implementation yet.
It'll be a while (probably till the end of the week) until I have time to debug that, but I will keep you posted in case it's an error on the server side.
