### ISSUE TITLE
add a setting for disabling autocomplete in comments

### ISSUE THREAD

**Issue by michaelkonecny** [hansec/fortran-language-server#43]
Typically, a natural language is used when commenting code and symbol names are seldom used, so having autocomplete pop up for every word can get a bit annoying/distracting.

Could there be a setting to "disable autocomplete in comments"?

**Comment by hansec** [comment]
Autocomplete should be disabled in comments. If you are getting autocomplete results from `fortls` in commented code can you give me example code so I can look into it?

Keep in mind that some editors have multiple autocomplete providers so the suggestions you are seeing might be from a different package. You can usually distinguish between them by the object type information that `fortls` provides.

**Comment by michaelkonecny** [comment]
You're right, sorry about this.

It was the Atom's [autocomplete-plus](https://atom.io/packages/autocomplete-plus) package, which was suggesting symbols it knew for the language + anything in document outline.

The solution was to add `.comment` to Scope Blacklist in the package settings.
