### ISSUE TITLE
Add parent scope related information in case of masked variable

### ISSUE THREAD

**Issue by daloic** [hansec/fortran-language-server#48]
You can find the patch. It is is pretty simple, when the masking is detected, the information about the parent is added to the error list to be used in the related information of the error message. This allows direct access to the reference from with Visual Studio Code as shown on the attached screenshot.

![Visual Studio Screenshot](https://user-images.githubusercontent.com/31305575/45644358-ddf1d980-babd-11e8-8e62-af877046a6d4.png)

[0001-Added-parent-scope-related-information.patch.txt](https://github.com/hansec/fortran-language-server/files/2389889/0001-Added-parent-scope-related-information.patch.txt)

**Comment by hansec** [comment]
Thanks for the contribution! I will definitely add feature. However, I am on vacation right now so it will be a week or so until I get the chance.
