### ISSUE TITLE
Visual Studio Code

### ISSUE THREAD

**Issue by BabaYara** [hansec/fortran-language-server#6]
I am about to begin work on a Fortran Language server for Visual Studio code. I wanted to know if your service works for VS code, so I can just fork it and move on from there.

Thank you.

Fahiz

**Comment by hansec** [comment]
It should work with VS code, Microsoft is who started the interoperable [language-server specification](https://github.com/Microsoft/language-server-protocol) that this package implements. You shouldn't need to make any modifications to this package. I looked into this before but I haven't had any time to work on it. I believe all you need to do is write the "client" side VS code extension (similar to the [atom package](https://github.com/hansec/ide-fortran)) that launches and communicates with the server.

**Comment by hansec** [comment]
I finally got around to making an [extension for VS code](https://marketplace.visualstudio.com/items?itemName=hansec.fortran-ls). Check it out and let me know if you run into any issues.
