### ISSUE TITLE
Parameter highlighting problem with array constructors

### ISSUE THREAD

**Issue by manie204** [hansec/fortran-language-server#60]
When passing an array via on-the-fly construction using the `[data_type:: a,b,c]` syntax to a function or subroutine, the tooltip gets confused. Each comma used in the array constructor skips to the next suggested function parameter. In the example picture below, the tooltip shows parameter `b`, even though we are still in the array constructor of argument `a`.
![image](https://user-images.githubusercontent.com/43782561/46349438-51fdb700-c652-11e8-847e-5cbcfde782b2.png)

**Comment by hansec** [comment]
Thanks for the report, I had never seen this syntax before. Do you have a reference to this feature definition in compiler documentation or somewhere so I can be sure to support all the possible syntax forms?

**Comment by manie204** [comment]
Sure, I had to look it up myself as there is a zoo of different array-related syntax out there. The syntax `[a,b,c]` is part of the Fortran 2003 standard and is AFAIK equivalent to the older `(/a,b,c/)` constructor.
A good resource explaining the syntax as well as covering some other ways of initializing arrays can be found at <https://software.intel.com/en-us/node/678554>.
If you happen to have a copy of the _Fortran 2003 Handbook_ by Adams et. al., the syntax is explained in detail in section _4.5. Array Constructors_.
I hope these resources are helpful.

**Comment by manie204** [comment]
Thank you for the effort. I really appreciate the work you put in.
