### ISSUE TITLE
Deferred-length character not recognized

### ISSUE THREAD

**Issue by manie204** [hansec/fortran-language-server#61]
A deferred-length allocatable string of characters is not recognized, i.e., there is no suggestion for ```some_string``` after using the following declaration:
```Fortran
character(:), allocatable :: some_string
```
The feature is part of the standard since Fortran 2003 but there seems to be relatively little documentation on it. I don't know of any other way of declaring it.

**Comment by hansec** [comment]
Thanks for the report! I just released a version (0.9.1) that should fix this issue. Let me know if you still see the problem after updating to the new version.
