### ISSUE TITLE
Windows 10, Python37, Atom test_source not running

### ISSUE THREAD

**Issue by JHenneberg** [hansec/fortran-language-server#65]
Hey,
i am in the process of setting up my FORTRAN IDE in Atom. Unfortunately the fortls seems not be running in my case. I installed Python37 and the fortran-language server with pip. In Atom i set the path of the executable to ..\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\fortls\__init__.py. When I am adding the test_source no and opening the outline dialog I am getting the error msg 'No outline available' although a popup is indicating that fortls is running before. Do I miss smth?

Python 37
Fortranlanguageserver 9.2 (via pip)
atom-ide-ui 0.13.0
ide-fortran 0.30
language-fortran 2.1.7

**Comment by hansec** [comment]
Thanks for the report. The `__init__.py` script is not the same as the executable and it should not be called directly. If you installed the language server using `pip` then a command called `fortls.exe` should have also been installed in the Python scripts directory. This directory is usually something like `C:\Python37\Scripts`. You can also find the scripts directory by looking in the directory containing the Python interpreter.

**Comment by JHenneberg** [comment]
Thank you so much. Did not expect such a fast answer. This is a realy usefull tool for every FORTRAN developer.
 This was the mistake the correct path is:
`c:\Users\<USER>\AppData\Local\Programs\Python\Python37-32\Scripts\fortls.exe `

**Comment by hansec** [comment]
No problem, I'm glad you like it!
