### ISSUE TITLE
incorrect detection of multiple declarations 

### ISSUE THREAD

**Issue by sunt05** [hansec/fortran-language-server#7]
For Fortran code with preprocessing `#ifdef` tags, false alarm such as  `sth. declared twice` will be issued.
Say for the following snippet, which is correct:
```
#ifdef nc
  INTEGER, PARAMETER:: MaxNumberOfGrids=90000   !Max no. grids   !TS changed to 90000 for large-scale simulation based on netCDF IO
#else
  INTEGER, PARAMETER:: MaxNumberOfGrids=2000   !Max no. grids   !HCW changed to 2000 from 10000 so prog can run on windows (2GB lim)
#endif 
```
 `fortls` will give error information in the diagnostics panel:

> Variable "MaxNumberOfGrids" declared twice in scope

**Comment by hansec** [comment]
This is definitely something I run into as well. However, I am hesitant to try and support too many preprocessing features as it could quickly become very cumbersome.

How valuable to you is more complete support for preprocessing as opposed to say disabling errors/warnings in preprocessed blocks? For example do you run into a lot of instances where the type of a variable or imported modules change based on preprocessor flags (such that autocomplete should be affected)? In the codes I work with the later is pretty infrequent, and handling it is much more involved.

**Comment by sunt05** [comment]
I think an option to disable certain errors detected by `fortls` (e.g., these ones due to preprocessing blocks) could be more valuable and feasible: as preprocessing is more a job owing to the compiler rather than the language server. Also, with proper settings in `linter`, most sensible errors/warnings can already be handled and displayed in the `Diagnostic` panel.
