### ISSUE TITLE
Please help me install it on an internet-free computer

### ISSUE THREAD

**Issue by smartsara** [hansec/fortran-language-server#71]
in order to install it on an off-line computer, i download the package in advance and then install it through  commands below:

-   cd  [work directory]
-   python setup.py build
-   python setup.py install

during the installation, however, the console show me some something seem like "can't find argparse package " or suchlike warnings. i think it may arise from  the loss of the dependencies.  so, can someone help me to fix this problem? the concern is how to make a full package with all dependencies in, and  how to install it offline. thanks a lot.

**Comment by hansec** [comment]
The language server only supports Python 2.7+, which should have the `argparse` package included. If you are using Python 2.6 or earlier you may be able to install the dependencies manually. However, the package has not been tested on earlier versions of Python so it may not work. If possible, I would suggest installing Python 2.7 or Python 3.4 instead.

**Comment by smartsara** [comment]
thanks for your reply. the python that i have on my computer is 3.7 and it is the latest release. it looks somewhat weird to me that the newer version doesn't go well with the language server as the old ones. nonetheless, i'll follow your advice to have another try with python 3.4 soon.
by the way,  how could i know the language server have come into work on my computer? i mean, are there any configurations that i have to do when i finish the installation? forgive me for this ridiculous question, as a vscode-and-fortran beginner, i find it really a big problem for me.

**Comment by hansec** [comment]
You shouldn't need to install Python 3.4 if you have Python 3.7. Python 3.7 includes the `argparse` package so if setup cannot find it then there is another problem. If you installed Python 3.7 yourself make sure you are using that and not the system Python version, which may be an earlier version.

What OS are you using? If you are on linux after installing the language serve you should be able to run `fortls --help` to make sure it installed properly.

**Comment by smartsara** [comment]
My OS is windows 7. When I run **fortls --help**,  the console reads "**usage: fortls [h]……**". Does that mean I have install it properly?

**Comment by smartsara** [comment]
And in the **setting** menu of Visual Studio Code,  I find an option for **Path to fortran-language-server (fortls)** under **FORTRAN IntelliSense**, should I leave textbox with default or post the path to fortls there?

**Comment by hansec** [comment]
On windows, make sure that when you run `fortls --help` you are not in the language server source folder. If the command `fortls` is available globally in your command prompt then the language server has been installed correctly and should work in VSCode. Note that you may need to specify the path to the installed script see issue #65 for more info on this.

**Comment by smartsara** [comment]
Sincere thanks for your patience and detailed answer. I'll try it again.

**Comment by hansec** [comment]
Since it has been a while I am going to close this issue. Let me know if you have any more questions.
