### ISSUE TITLE
Associate not recognized 

### ISSUE THREAD

**Issue by PaulXiCao** [hansec/fortran-language-server#72]
Today I installed the current version 1.0.0 and suddenly warnings pop up around `associate` blocks.

Example code:
```fortran 
program main

  implicit none

  associate( x=>1 )
  end associate               ! this is line 6

end program main
```

Warning message: 

> Unexpected end of scope at line 6

**Comment by hansec** [comment]
Thanks for the report! This issue should be fixed in the most recent patch (1.0.1).
