### ISSUE TITLE
"selectcase" as one word causing problems

### ISSUE THREAD

**Issue by emanspeaks** [hansec/fortran-language-server#77]
"SELECTCASE" and "ENDSELECT" as single keywords with no space are considered valid Fortran.  Some legacy code containing these single word uses were resulting in a number of diagnostic errors of "unexpected end of scope"

**Comment by hansec** [comment]
Thanks for the report. Yep, this was just a typo that should be fixed in master now. It will be included in the next patch (likely later today).
