### ISSUE TITLE
 Named select case not detected

### ISSUE THREAD

**Issue by Edmundod** [hansec/fortran-language-server#80]
Named `select case` is not recognized by fortls, while `if` and `do` are. Consider the following:

```fortran-modern
program test

  one: select case ("it is NOT working")
    case default

  end select one

  select case ("it is working")
    case default

  end select

  two: if (2==3) then

  end if two

end program test
```
where the first `select case` is not visible to fortls, while the second one is. With `if` everything works. It can be seen in debugger output:
```
=========
Parser Output
=========

program test !!! PROGRAM statement(1)
end select one !!! END "SELECT" scope(6)
select case ("it is working") !!! SELECT statement(8)
end select !!! END "SELECT" scope(11)
two: if (2==3) then !!! IF statement(13)
end if two !!! END "IF" scope(15)
end program test !!! END "PROGRAM" scope(17)

=========
Object Tree
=========

1: test
9: main::#select1
12: main::#if1

```

**Comment by hansec** [comment]
Thanks for the report. This should now be fixed in master and will be included in the next patch.

**Comment by Edmundod** [comment]
You are fast as hell :) Thanks!

**Comment by JHenneberg** [comment]
he is :) but who is anyway using name selects? What is the real benefit of this if you use decent naming for al of your variables?

**Comment by Edmundod** [comment]
Mostly when using subselects I find it easier to read with naming. It's not a very big deal, but it's a Fortran standard, hence this issue.

**Comment by JHenneberg** [comment]
ok I see :). If it is according to the standard then it should be implemented fully agree.
