### ISSUE TITLE
Parser failing, possibly due to variable named "END"

### ISSUE THREAD

**Issue by emanspeaks** [hansec/fortran-language-server#82]
I have a file still tripping up parsing that may be due to a variable named `END` causing problems.  Again, this is in a legacy package for which I cannot change the code in this file.  I stripped the code down to its basics and mangled the logic to create an example that recreates the essential problem. I do not claim that this example code makes any sense or even compiles, ha ha, but it essentially follows the control flow of the original and should at least parse correctly.

```fortran
      INTEGER FUNCTION  TEST ( )
      INTEGER          BEGIN
      INTEGER          END
      BEGIN = 1
      END   = 0
      IF      ( BEGIN .LE. 0 ) THEN
         TEST = 0
         RETURN
      ELSE
         DO WHILE ( BEGIN .GT. 2 )
 
            BEGIN    = 2
            IF ( BEGIN .LT. 1 ) THEN
               BEGIN  = 3
            ELSE
               END    = 1
            END IF
            BEGIN     = 1 + ( END - BEGIN )
         END DO
         IF ( BEGIN .LT. 1 ) THEN
            TEST = BEGIN
         ELSE
            TEST = END
         END IF
      END IF
      DO WHILE (TEST .LT. 2 .AND.
     .          TEST .EQ. 1 )
         TEST = TEST + 1
      END DO
      RETURN
      END
```

**Comment by hansec** [comment]
Yep, should be fixed in the next release. Although, if this is your code I would not suggest using `END` as a variable name. Generally, using language keywords as variables isn't the best idea. Of course, I have seen a lot of old libraries (especially in Fortran) where people don't agree with that sentiment.

**Comment by emanspeaks** [comment]
Yup, this is not code I have any control over or I would have just changed it!  It's very much legacy code that I need to use in some of mine, and I wanted to prevent all the fortls errors I can!

**Comment by emanspeaks** [comment]
Meant to add that I confirm this is now fixed.  Thanks!
