### ISSUE TITLE
Peek Reference don't include assigning values to variables

### ISSUE THREAD

**Issue by lonelykid** [hansec/fortran-language-server#84]
The Find All References and Peek References provide references to variables. However, from my observation, that doesn't include statements assigning values to variables (eg. x=1). I'm not sure this should be considered. But when I read code, it's helpful if I could find its value easily. Of course I can use the find in files provided by editor.

Another issue is that I found you cannot find its references if a variable is used as a loop variable. This is as expected. I just want to make sure this behavior is intentional.

BTW, could you add some other methods for donation? I do like this project but Paypal doesn't like me; they've banned me😂.

**Comment by hansec** [comment]
Thanks for the report. I think I tracked down the first issue. It looks like the language server is getting tripped up when the line starts with the variable it is searching for. Can you try adding a leading space in situations where assignments aren't found and confirm that fixes the issue for you.

I am not entirely clear what you mean by "used as a loop variable". Are you saying you wouldn't get any results for the variable "foo" in the example code below. All references are shown for me (note I added a leading space to the last assignment line. Keep in mind that "Find All References" is limited to top-level objects (variables, types, subroutines, etc.) in modules/programs.

```fortran
PROGRAM test
INTEGER(4) :: foo,i
DO foo=1,10
  i=i+foo
END DO
 foo = i-1
END PROGRAM test
```

If you can use Venmo my username is the same as my Github username. Don't worry about it though, not looking for actual donations to support development just the digital version of "buy me a beer".

**Comment by lonelykid** [comment]
@hansec Thank you! Your fix works!
As for the second issue, you are right. That's because my loop variable is defined in a subroutine in a module. Is this your design or there's some technical difficulty?

**Comment by hansec** [comment]
It was just the easiest thing to do. I plan to add local variable search too, but I just haven't gotten around to it yet. I figured "globally" accessible objects would be the most useful thing first.

Also, thanks for the :beer:!

**Comment by hansec** [comment]
@lonelykid It actually turned out to be pretty easy to enable "references" for most other variables. This feature will be included in the next release, hopefully tomorrow. With this change the only remaining items that aren't supported in find references are user-defined type members.

**Comment by lonelykid** [comment]
@hansec Great work! I'm not opening heavy IDE's for my Fortran project now.
