### ISSUE TITLE
Components missing in class hierarchy

### ISSUE THREAD

**Issue by mscfd** [hansec/fortran-language-server#85]
Completion suggestions in emacs after typing "some_arg%" (as already done at the end of the code below), gives all the choices from my_type_3 and my_type_2, but not from my_type_1 (so some_var is not suggested as it should be). I guess fortls is providing an incomplete list.

```
module mod

implicit none
private

type, public :: my_type_1
   integer :: some_var
end type my_type_1

type, extends(my_type_1), public :: my_type_2
   real :: realvalue
   class(xyz), pointer :: uvw
end type my_type_2

type, extends(my_type_2), public :: my_type_3
   class(xyz), pointer :: abc
end type my_type_3

contains

subroutine bar(some_arg)
   class(my_type_3), intent(in) :: some_arg

   some_arg%
end subroutine bar
```

**Comment by hansec** [comment]
Thanks for the report! There was a bug in recursive inheritance. A fix will be included in the next patch.
