### ISSUE TITLE
AttributeError with out of range position at command line for --debug_references

### ISSUE THREAD

**Issue by mscfd** [hansec/fortran-language-server#86]
This is a really uninteresting bug. An AttributeError exception is raised if I call fortls with out of range position arguments as in
fortls --debug_references --debug_filepath some.f90 --debug_line 123456 --debug_char 123456

With other debug options the out of range problem is caught.

**Comment by mscfd** [comment]
I just noticed that the AttributeError also happens if the position is not on some proper object, e.g. on a empty space, or some '::' delimiter. So this might be more serious than initially assumed.

(For example invoking lsp-find-references in emacs with the cursor on some '::' triggers this error from the editor.)

**Comment by hansec** [comment]
Thanks for the report. I have just pushed a fix for this issue that will be included in the next patch.
