### ISSUE TITLE
No hover information for type-boundary procedure  without "=>" reference in declaraion

### ISSUE THREAD

**Issue by mscfd** [hansec/fortran-language-server#89]
For the code below

fortls --debug_rootpath . --debug_hover --debug_filepath test2.f90 --debug_line 18 --debug_char 14

gives a proper type signature for subroutine car, but

fortls --debug_rootpath . --debug_hover --debug_filepath test2.f90 --debug_line 13 --debug_char 14

fails. This is due to the missing "=> dar", which is present for car. I can see that the proper object is present at langserver.py, line 1211 (tag 1.2.1), but it has var_type==7 (in contrast to var_type==2 for car). For car link_obj is set and obviously points to a fortran_subroutine object, whereas for "dar" there is no link.

A bug fix could be:
https://github.com/mscfd/fortran-language-server/commit/67cab82bb4aa6fcd2d11a2bc6692a32082ede220

but I have to admit, that I do not grasp all the relations in this spaghetti routine, where I made the change.

```
module mod

type mytype
contains
   procedure, public :: car => car
   procedure, public :: dar
end type mytype

contains

subroutine car(self)
   class(mytype) :: self
   call self%dar()
end subroutine car

subroutine dar(self)
   class(mytype) :: self
   call self%car()
end subroutine dar

end module mod
```

**Comment by hansec** [comment]
Thanks for the report. This should now be fixed in master and will be included in the next release.
