### ISSUE TITLE
Allow empty lines within continuation

### ISSUE THREAD

**Issue by mscfd** [hansec/fortran-language-server#91]
At the very end of the code below (cursor after ```param_```), the completion list should contain all param_ variables, but param_ccc is missing. The empty line with the comment does not break the continuation, but the completely empty line does. Both are allowed within continuation lines.

```
module

integer, parameter :: &
      param_aaa = 1, &
      param_bbb = 2, &

      param_ccc = 3

real, parameter :: &
      param_ddd = 1.0, &  !comment
                          !comment
      param_eee = 2.0

contains

   subroutine sub()
      param_
```

**Comment by hansec** [comment]
Thanks for the report. This should now be fixed in master and will be included in the next release.
