### ISSUE TITLE
one line WHERE statement not recognized

### ISSUE THREAD

**Issue by JHenneberg** [hansec/fortran-language-server#92]
The one line version of a WHERE statement is not detected

```
WHERE (ABS(A) < 1D-6) A = 0.0D0
```

**Comment by hansec** [comment]
Thanks for the report. This should now be fixed in master and will be included in the next patch.

**Comment by hansec** [comment]
There was a typo in the previous commit, see fix above.

**Comment by JHenneberg** [comment]
ah ok thanks a lot
