### ISSUE TITLE
unable to find definition in some cases

### ISSUE THREAD

**Issue by lonelykid** [hansec/fortran-language-server#93]
I find some cases it cannot find definition when dealing with this antique code. I will try if I can isolate the problem. Does this remind you of anything?
![bug](https://user-images.githubusercontent.com/2936633/53672162-4806d100-3c4f-11e9-9a24-10a0aa1be213.gif)
If I try multiple times, it might or might not go to definition. If I select the name, it can always go to the definition.

![bug1](https://user-images.githubusercontent.com/2936633/53672165-4d641b80-3c4f-11e9-98d6-7ac3f95cfc21.gif)
The definition could be found and shown in the pop out. But if I try again, it disappeared.

**Comment by hansec** [comment]
Hmmm, unfortunately I have not seen this type of behavior. It looks like you are using Atom, however the [Atom IDE support](https://ide.atom.io/) that the language server uses is currently in limbo. Can you try VSCode or another editor and see if you get the same issues?

**Comment by lonelykid** [comment]
@hansec I'm using vscode. I would try to isolate the problem so you can have a try.

**Comment by hansec** [comment]
Gotcha, that was the only immediate idea I had. Sometimes I have noticed a lag in definitions, hover and other requesting being available after an edit, but never just appearing and disappearing without file changes.

One thing to look into is using the [debug log option](https://github.com/hansec/fortran-language-server#configuration) to see if the definition request is getting a response or if the "missing" result is due to the response taking too long. Make sure you turn off `debug_log` when you are done, as it can generate rather large files if you are editing for an extended period of time with it enabled.

**Comment by hansec** [comment]
@lonelykid Have you been able to get any additional information on this issue? Are you still seeing it?

**Comment by lonelykid** [comment]
This is what happened when I try going to definition directly
DEBUG:fortls.jsonrpc:RECV {"jsonrpc":"2.0","id":5,"method":"textDocument/definition","params":{"textDocument":{"uri":"file:///c%3A/Users/xxx/xxx/Main.f90"},"position":{"line":303,"character":10}}}
DEBUG:fortls.langserver:REQUEST 5 textDocument/definition
DEBUG:fortls.jsonrpc:SEND {"jsonrpc":"2.0","id":5,"result":null}

This is when I selected the name and tried going to defintion
DEBUG:fortls.jsonrpc:RECV {"jsonrpc":"2.0","id":8,"method":"textDocument/definition","params":{"textDocument":{"uri":"file:///c%3A/Users/xxx/xxx/Main.f90"},"position":{"line":303,"character":15}}}
DEBUG:fortls.langserver:REQUEST 8 textDocument/definition
DEBUG:fortls.jsonrpc:SEND {"jsonrpc":"2.0","id":8,"result":{"uri":"file:///c%3A/Users/xxx/xxx/Marquardt.f90","range":{"start":{"line":14,"character":11},"end":{"line":14,"character":17}}}}

Then I find out this depends on where I move my cursor to.
![image](https://user-images.githubusercontent.com/2936633/55629427-2d110a80-5781-11e9-9777-9e886359f3d9.png)

**Comment by hansec** [comment]
Hmmm, is there any chance you could reproduce this in a smaller test case where you could send me the code?

**Comment by lonelykid** [comment]
I spent some time to figure out what's wrong. It turns out this is due to indentation. Converting indentation to spaces makes it work.
[demo1.zip](https://github.com/hansec/fortran-language-server/files/3049162/demo1.zip)
![image](https://user-images.githubusercontent.com/2936633/55648536-952a1580-57ae-11e9-9a70-f11c8cc27e69.png)
![image](https://user-images.githubusercontent.com/2936633/55648551-9c512380-57ae-11e9-82f7-88f9ba7693bc.png)

**Comment by hansec** [comment]
Great, this should now be fixed in master and will be included in the next patch. Let me know if you continue to observe this issue. Thanks for the report and debugging!

**Comment by lonelykid** [comment]
Thank you! I can confirm it is fixed.
