### ISSUE TITLE
Preprocessor line-continuation issue

### ISSUE THREAD

**Issue by manie204** [hansec/fortran-language-server#98]
When defining a preprocessor macro, it is possible to continue the definition on the next line using a single backslash as the last symbol of the line. For example,
```Fortran
#define SOME_MACRO A = B + \
C
```
It seems that this is not parsed correctly by the language server. Here is an MWE containing a macro that defines a whole subroutine over multiple lines:
```Fortran
module test_module
contains

#define SOME_MACRO subroutine foo() ;\
      write(*, *) 'Hello World!' ;\
   end subroutine

   SOME_MACRO
end module test_module

program test_program
   use test_module
   call foo
end program test_program
```
The language server incorrectly assumes that the line containing ```end subroutine``` closes a scope that was never opened. As a result it is not able to correctly identify the scope of the whole module.

**Comment by hansec** [comment]
Thanks for the report! This should now be fixed in master and will be included in the next patch. Let me know if you continue to run into issues.
